### ISSUE TITLE
Pipeline crashes when at least one of the images contains no ice floes

### ISSUE THREAD

**Issue by danielmwatkins** [WilhelmusLab/ice-floe-tracker-pipeline#109]
This is a key issue that was first noticed a while ago but I don't see listed in the issues. I'm not sure yet whether it belongs in the IFT.jl or IFT-pipeline. The issue appears anytime you try to run a sequence of images that have at least one image with no detected floes, which can occur in many scenarios: full cloud cover, all detected floes are too small, floes are too close to each other to be distinguished, for example. It should be a simple fix -- if you know where to change in the code. I think it's an issue with how Julia DataFrames handles empty dataframes. For example, if IFT finds floes, and they are all below the minarea setting, then the dataframe will have no rows. When sort() is called, instead of just returning the empty set, Julia throws an error and crashes.

**Comment by tdivoll** [comment]
@danielmwatkins, this issue might be solved now after PR #114?

**Comment by danielmwatkins** [comment]
It's almost there! Talking with Carlos now about the issue that then shows up in the tracker module.

Basically:
1. Image has no floes detected
2. Error in preprocess fixed -- a blank image is created
3. When an image is blank, the feature props data frame doesn't get the latitude/longitude columns added to it
4. IFT crashes saying "column not found".
Once this last bug is fixed, then then pipeline should be able to keep running.

**Comment by cpaniaguam** [comment]
Can this issue be closed in light of https://github.com/WilhelmusLab/IceFloeTracker.jl/pull/363?

**Comment by tdivoll** [comment]
@danielmwatkins, Do you want to close this issue? See the comment above from @cpaniaguam; this was handled in the source code rather than the pipeline.
