### ISSUE TITLE
fetchdata settings

### ISSUE THREAD

**Issue by danielmwatkins** [WilhelmusLab/ice-floe-tracker-pipeline#14]
A couple things with the fetchdata script -
1. The script exits if a landmask file is in the directory, even if the dates of the download are different. There should be an option to overwrite the landmask, or a prompt to ask if it should be overwritten, or something like that.
2. Using open ended inputs for the bounding box is potentially a problem. It assumes that the coordinates are given with latitude first, then longitude. If a negative latitude is provided (say, bounding box -60, 10, -80, 20, which would select somewhere in Antarctica probably) then it fails saying "unrecognized input -6". I actually ran into the issue trying because I'd written the longitude first since it specified the order as X coordinate then Y coordinate, and that would imply writing longitude first. It would be good to be able to specify bounds just as e.g. -left, -right, -top, -bottom.

**Comment by tdivoll** [comment]
I believe #13 fixes this. Let's wait until it is merged and test the overwrite. There are now comments in the `flow.cylc` file and the `README` to help with the lat/lon -> x,y issue.
