### ISSUE TITLE
Address H5 file size issue

### ISSUE THREAD

**Issue by danielmwatkins** [WilhelmusLab/ice-floe-tracker-pipeline#142]
Conversion to .h5 results in images that are ~4x as large (e.g., the labeled image for a 64MB truecolor image is 505MB), despite containing far less information. A likely cause is h5 naively assuming that we want to have the array in 64 bit floats rather than integers.

**Comment by cpaniaguam** [comment]
Here is the distribution of a sample archive.
```julia
8×3 DataFrame
 Row │ object                         size     relsize 
     │ String                         Int64    Float64 
─────┼─────────────────────────────────────────────────
   1 │ floe_properties.labeled_image  1223088    33.25
   2 │ index.latitude                 1223088    33.25
   3 │ index.longitude                1223088    33.25
   4 │ index.x                           3168     0.09
   5 │ index.y                           3168     0.09
   6 │ floe_properties.properties        2920     0.08
   7 │ floe_properties.column_names       288     0.01
   8 │ index.time                           8     0.0
```

Lat/Lon matrices will be removed from the index and the type for `labeled_image` will be selected adaptively so as its size minimized.
