### ISSUE TITLE
Download cloudmask with new a Python script

### ISSUE THREAD

**Issue by tdivoll** [WilhelmusLab/ice-floe-tracker-pipeline#147]
Download the cloudmask product rather than generate it with Fetchdata.sh.

- This will still need the second half of the cloudmask CLI wrapper
- Will allow FSD to just use the downloaded cloudmask product

**Comment by mirestrepo** [comment]
- [ ] Images - TCI, FCI, landmasks
- [ ] Cloudmask

**Comment by hollandjg** [comment]
Done in #198
