### ISSUE TITLE
Update to latest Cylc version

### ISSUE THREAD

**Issue by tdivoll** [WilhelmusLab/ice-floe-tracker-pipeline#154]
Test the current pipeline with the latest Cylc version 8.3.3, which would be an upgrade from 8.2.1.

- If all current tasks pass, update the `ift-env.yml` for user Cylc install

**Comment by tdivoll** [comment]
[job.err.txt](https://github.com/user-attachments/files/16480647/job.err.txt)

**Comment by tdivoll** [comment]
With some further testing, it seems like this only fails on certain image sets. Some HDF5 files created and others fail, even with Cylc 8.2.1.

**Comment by tdivoll** [comment]
This could be related to #145 if certain dates don't have the overpass times; test again after that issue is resolved.

**Comment by hollandjg** [comment]
Works with #198
