### ISSUE TITLE
Test local Cylc workflow on Windows

### ISSUE THREAD

**Issue by tdivoll** [WilhelmusLab/ice-floe-tracker-pipeline#49]
We need to test the workflow for `Running Cylc pipeline locally` on Windows to make sure everything builds/runs.

**Comment by cpaniaguam** [comment]
@tdivoll I could try that. Are there instructions on how to do this?

**Comment by tdivoll** [comment]
That would be great! Hopefully the `Running the Cylc pipeline locally` section in the readme has all the necessary steps. Let me know if anything doesn't make sense and I can update the readme for clarity. I'm expecting some Windows-specific caveats that we might need to add to the README.

**Comment by cpaniaguam** [comment]
@tdivoll I am experiencing issues installing cycl on Windows.

Using the yml file:
```
(base) C:\ice-floe-tracker-pipeline>conda env create -f config\ift-env.yaml
Collecting package metadata (repodata.json): done
Solving environment: -
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed

ResolvePackageNotFound:
  - __unix


(base) C:\ice-floe-tracker-pipeline>
```

Creating the env by hand and then installing cycl:
```
(base) C:\ice-floe-tracker-pipeline>conda activate ift-env
(base) C:\ice-floe-tracker-pipeline>conda list
# packages in environment at C:\Users\cpaniagu\Anaconda3\envs\ift-env:
#
# Name                    Version                   Build  Channel
(base) C:\ice-floe-tracker-pipeline>conda install --channel=conda-forge cylc-flow
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: - 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed

UnsatisfiableError: The following specifications were found to be incompatible with your system:

  - cylc-flow -> __unix

Your installed version is: not available


(base) C:\ice-floe-tracker-pipeline>
```
I tried on my normal windows computer and on a windows vm.

I guess `cycl` only runs on Unix based systems? I am also trying on WSL as I type this:

```
(base) root@CIS14Y0NRQ3:/mnt/c/ice-floe-tracker-pipeline# conda install --channel=conda-forge cylc-flow
Collecting package metadata (current_repodata.json): -done
Solving environment: unsuccessful initial attempt using frozen solve. Retrying with flexible solve.
Solving environment: unsuccessful attempt using repodata from current_repodata.json, retrying with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: [spinner]
```
It's been stuck there for a long time (at least an hour).

**Comment by tdivoll** [comment]
I think you are right. I thought it might work with WSL, but I think the filesystem for WSL is still on Windows. I did find this `won't fix` issue, so I think we've covered our bases. Cylc for IceFloeTracker will need to be run on local Mac or Unix, or on Oscar (or other HPC). 
![image](https://github.com/WilhelmusLab/ice-floe-tracker-pipeline/assets/24841909/8b09eb03-71f0-4763-96bb-3d5a9335ed3d)

**Comment by tdivoll** [comment]
Thank you for testing @cpaniaguam!
