### ISSUE TITLE
[Experimental] Do lat long externally in py

### ISSUE THREAD

**Issue by cpaniaguam** [WilhelmusLab/ice-floe-tracker-pipeline#52]
Pyproj not building in container

**Comment by cpaniaguam** [comment]
Recover manifest to retrieve IFT version.

**Comment by cpaniaguam** [comment]
@tdivoll Here is a new idea to retrieve IFT version. It's Project.toml records its version. Maybe we can get it from there.

**Comment by cpaniaguam** [comment]
@tdivoll Here is a new idea to retrieve IFT version. It's Project.toml records its version. Maybe we can get it from there.

**Comment by tdivoll** [comment]
Fixed by #63
